name: Firebase Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: Verify Build Output
        run: ls -la build # Debugging step to confirm build output

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/ # Ensure the path is correct

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - name: Verify Downloaded Files
        run: ls -la build # Debugging step to check if the artifact was downloaded

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
